# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "You don't need to be coy, COI!"
subtitle: "This is a template for SoBigData Master's projects"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


# Riportare il github del gruppo di progetto e quello del sito web (se differente).
# Tali informazioni appariranno nel Footer del sito.
github_repo:
  - name: "g2-2025-website"
    url: "https://github.com/GiovannaAndreucci/g2-2025-website/"

markdown: kramdown

baseurl: "/g2-2025-website"
#baseurl: ""
url: "https://GiovannaAndreucci.github.io"

#################################
#    Navigation configuration   #
#################################

navbar:
  style :  dual #don't change this, it is used to set the navbar style.
  brand: # this is the brand of the navbar, it will be displayed on the left side.
    title :  "You don't need to be coy, COI!"
    img: "./assets/images/Logo_masthead.png" # don't change this
    url: /
  nav:
    #- title: Guide
    #  url: /guide.html
    - title: Articolo
      url: /example.html
    #- title: Another ex page
    #  url: /new_page.html
    - title: Report tecnico
      child:
        - title: Scraping and Geolocation
          url: /scraping.html
        - title: Medical Area Extraction
          url: /aree_med.html
        - title: Company Extraction
          url: /aziende.html
        - title: Graph and Community
          url: /folium.html
        #- title: Sliders
        #  url: /slider.html

    - title: SBD Master # this must be always the last item in the navbar, don't change it
      url: https://masterbigdata.it/

###########################
#    General appearance   #
###########################

googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,700;1,400;1,700&display=swap"
  - url: "https://fonts.googleapis.com/css2?family=Charm:ital,wght@0,400;0,700;1,400&display=swap"


chulapa-skin:
  skin: "chulapa"
  #primary: "#e8c28aff"
  #vars:
    #font-family-base:  "EB Garamond, serif"
   #heading-font-family: "Charm, cursive"



##################################################
#    Don't change anything below this line    #
##################################################

# Build settings
#theme: chulapa-jekyll # va usato il remote-theme!!!
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path

footer:
  links:
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: https://www.linkedin.com/company/sobigdata
  - label: "Twitter"
    icon: "fab fa-twitter"
    url: https://www.twitter.com/sobigdata
  copyright: "2025 SoBigData RI"


sass:
  quiet_deps: true

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea/


livereload: true

remote_theme: dieghernan/chulapa

future: true

defaults:
  - scope:
      path: "assets/images/thumb-charts"
    values:
      image_col: charts
